// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTmLbpPB_R6WJjEwXJ0aPjhmlVo9Nx5E',
    appId: '1:29419941154:web:647611b2d82dc7668ec97b',
    messagingSenderId: '29419941154',
    projectId: 'okr-generator',
    authDomain: 'okr-generator.firebaseapp.com',
    storageBucket: 'okr-generator.appspot.com',
    measurementId: 'G-PLT9B0GVSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXHgrSOKYMnJe3BM5Ok1bLMnDtEMQzoU',
    appId: '1:29419941154:android:9f3d0baa77a97b098ec97b',
    messagingSenderId: '29419941154',
    projectId: 'okr-generator',
    storageBucket: 'okr-generator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5RT6a9th_xegXIuMp-7s0ewxGTc94jmM',
    appId: '1:29419941154:ios:30e6608fae4c5e948ec97b',
    messagingSenderId: '29419941154',
    projectId: 'okr-generator',
    storageBucket: 'okr-generator.appspot.com',
    iosClientId: '29419941154-vee9duesuu1m85t0cgte79jrllk2shai.apps.googleusercontent.com',
    iosBundleId: 'com.example.okrGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5RT6a9th_xegXIuMp-7s0ewxGTc94jmM',
    appId: '1:29419941154:ios:30e6608fae4c5e948ec97b',
    messagingSenderId: '29419941154',
    projectId: 'okr-generator',
    storageBucket: 'okr-generator.appspot.com',
    iosClientId: '29419941154-vee9duesuu1m85t0cgte79jrllk2shai.apps.googleusercontent.com',
    iosBundleId: 'com.example.okrGenerator',
  );
}
